# Kubernetes Pod Security Standards (PSS) Configuration
# Modern replacement for Pod Security Policies with enhanced security controls
# Based on CIS Kubernetes Benchmark v1.8.0 and NSA/CISA Kubernetes Hardening Guide

---
# Privileged Pod Security Standard (Baseline for critical system components)
apiVersion: v1
kind: Namespace
metadata:
  name: system-privileged
  labels:
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged
  annotations:
    scheduler.alpha.kubernetes.io/node-selector: "node-role.kubernetes.io/control-plane="

---
# Baseline Pod Security Standard (Default for most workloads)
apiVersion: v1
kind: Namespace
metadata:
  name: baseline-workloads
  labels:
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/audit: baseline
    pod-security.kubernetes.io/warn: baseline
    security.kubernetes.io/baseline: "true"
  annotations:
    pod-security.kubernetes.io/enforce-version: "v1.28"
    pod-security.kubernetes.io/audit-version: "v1.28"
    pod-security.kubernetes.io/warn-version: "v1.28"

---
# Restricted Pod Security Standard (Highest security for sensitive workloads)
apiVersion: v1
kind: Namespace
metadata:
  name: restricted-workloads
  labels:
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
    security.kubernetes.io/restricted: "true"
    compliance.kubernetes.io/cis-benchmark: "enabled"
  annotations:
    pod-security.kubernetes.io/enforce-version: "v1.28"
    pod-security.kubernetes.io/audit-version: "v1.28"
    pod-security.kubernetes.io/warn-version: "v1.28"
    security.kubernetes.io/seccomp-default: "RuntimeDefault"
    security.kubernetes.io/selinux-required: "true"

---
# Security-focused namespace for financial/PCI workloads
apiVersion: v1
kind: Namespace
metadata:
  name: pci-dss-workloads
  labels:
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
    compliance.kubernetes.io/pci-dss: "enabled"
    security.kubernetes.io/isolation: "strict"
  annotations:
    pod-security.kubernetes.io/enforce-version: "v1.28"
    network.kubernetes.io/isolation: "strict"
    security.kubernetes.io/encryption-required: "true"
    compliance.kubernetes.io/data-classification: "sensitive"

---
# Development namespace with baseline security
apiVersion: v1
kind: Namespace
metadata:
  name: development
  labels:
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
    environment: development
  annotations:
    pod-security.kubernetes.io/enforce-version: "v1.28"
    pod-security.kubernetes.io/audit-version: "v1.28"
    pod-security.kubernetes.io/warn-version: "v1.28"
    security.kubernetes.io/learning-mode: "enabled"

---
# Production namespace with strict security
apiVersion: v1
kind: Namespace
metadata:
  name: production
  labels:
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
    environment: production
    security.kubernetes.io/critical: "true"
  annotations:
    pod-security.kubernetes.io/enforce-version: "v1.28"
    pod-security.kubernetes.io/audit-version: "v1.28"
    pod-security.kubernetes.io/warn-version: "v1.28"
    security.kubernetes.io/monitoring: "enhanced"
    compliance.kubernetes.io/sox-compliant: "true"

---
# ClusterRole for security policy management
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pod-security-policy-manager
  labels:
    rbac.kubernetes.io/aggregate-to-admin: "true"
rules:
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "list", "watch", "create", "update", "patch"]
- apiGroups: ["policy"]
  resources: ["podsecuritypolicies"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["clusterroles", "clusterrolebindings", "roles", "rolebindings"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

---
# Service Account for security monitoring
apiVersion: v1
kind: ServiceAccount
metadata:
  name: security-monitor
  namespace: kube-system
  labels:
    app.kubernetes.io/name: security-monitor
    app.kubernetes.io/component: monitoring
automountServiceAccountToken: false

---
# ClusterRole for security monitoring
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: security-monitor
rules:
- apiGroups: [""]
  resources: ["pods", "nodes", "namespaces", "services", "endpoints"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets", "daemonsets", "statefulsets"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["networking.k8s.io"]
  resources: ["networkpolicies", "ingresses"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["policy"]
  resources: ["podsecuritypolicies"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["roles", "clusterroles", "rolebindings", "clusterrolebindings"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["security.openshift.io"]
  resources: ["securitycontextconstraints"]
  verbs: ["get", "list", "watch"]

---
# ClusterRoleBinding for security monitoring
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: security-monitor
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: security-monitor
subjects:
- kind: ServiceAccount
  name: security-monitor
  namespace: kube-system

---
# Security ConfigMap for baseline security configurations
apiVersion: v1
kind: ConfigMap
metadata:
  name: security-baseline-config
  namespace: kube-system
  labels:
    app.kubernetes.io/name: security-baseline
    app.kubernetes.io/component: configuration
data:
  seccomp-default.json: |
    {
      "defaultAction": "SCMP_ACT_ERRNO",
      "architectures": ["SCMP_ARCH_X86_64", "SCMP_ARCH_AARCH64"],
      "syscalls": [
        {
          "names": [
            "accept", "accept4", "access", "adjtimex", "alarm", "bind", "brk",
            "capget", "capset", "chdir", "chmod", "chown", "chroot", "clock_getres",
            "clock_gettime", "clock_nanosleep", "close", "connect", "copy_file_range",
            "creat", "dup", "dup2", "dup3", "epoll_create", "epoll_create1",
            "epoll_ctl", "epoll_pwait", "epoll_wait", "eventfd", "eventfd2",
            "execve", "execveat", "exit", "exit_group", "faccessat", "fadvise64",
            "fallocate", "fanotify_mark", "fchdir", "fchmod", "fchmodat", "fchown",
            "fchownat", "fcntl", "fdatasync", "fgetxattr", "flistxattr", "flock",
            "fork", "fremovexattr", "fsetxattr", "fstat", "fstatfs", "fsync",
            "ftruncate", "futex", "getcwd", "getdents", "getdents64", "getegid",
            "geteuid", "getgid", "getgroups", "getitimer", "getpeername", "getpgid",
            "getpgrp", "getpid", "getppid", "getpriority", "getrandom", "getresgid",
            "getresuid", "getrlimit", "getrusage", "getsid", "getsockname",
            "getsockopt", "gettid", "gettimeofday", "getuid", "getxattr", "inotify_add_watch",
            "inotify_init", "inotify_init1", "inotify_rm_watch", "io_cancel",
            "io_destroy", "io_getevents", "io_setup", "io_submit", "ioctl",
            "ioprio_get", "ioprio_set", "keyctl", "kill", "listen", "listxattr",
            "llistxattr", "lremovexattr", "lseek", "lsetxattr", "lstat", "madvise",
            "memfd_create", "mincore", "mkdir", "mkdirat", "mknod", "mknodat",
            "mlock", "mlock2", "mlockall", "mmap", "mprotect", "mq_getsetattr",
            "mq_notify", "mq_open", "mq_timedreceive", "mq_timedsend", "mq_unlink",
            "mremap", "msgctl", "msgget", "msgrcv", "msgsnd", "msync", "munlock",
            "munlockall", "munmap", "nanosleep", "newfstatat", "open", "openat",
            "pause", "pipe", "pipe2", "poll", "ppoll", "prctl", "pread64",
            "preadv", "prlimit64", "pselect6", "ptrace", "pwrite64", "pwritev",
            "read", "readahead", "readlink", "readlinkat", "readv", "recv",
            "recvfrom", "recvmmsg", "recvmsg", "removexattr", "rename", "renameat",
            "renameat2", "restart_syscall", "rmdir", "rt_sigaction", "rt_sigpending",
            "rt_sigprocmask", "rt_sigqueueinfo", "rt_sigreturn", "rt_sigsuspend",
            "rt_sigtimedwait", "rt_tgsigqueueinfo", "sched_getaffinity",
            "sched_getattr", "sched_getparam", "sched_get_priority_max",
            "sched_get_priority_min", "sched_getscheduler", "sched_rr_get_interval",
            "sched_setaffinity", "sched_setattr", "sched_setparam", "sched_setscheduler",
            "sched_yield", "seccomp", "select", "semctl", "semget", "semop",
            "semtimedop", "send", "sendfile", "sendmmsg", "sendmsg", "sendto",
            "setfsgid", "setfsuid", "setgid", "setgroups", "setitimer", "setpgid",
            "setpriority", "setregid", "setresgid", "setresuid", "setreuid",
            "setrlimit", "setsid", "setsockopt", "setuid", "setxattr", "shmat",
            "shmctl", "shmdt", "shmget", "shutdown", "sigaltstack", "signalfd",
            "signalfd4", "sigpending", "sigprocmask", "sigreturn", "sigsuspend",
            "socket", "socketpair", "splice", "stat", "statfs", "symlink",
            "symlinkat", "sync", "sync_file_range", "syncfs", "sysinfo", "tee",
            "tgkill", "time", "timer_create", "timer_delete", "timer_getoverrun",
            "timer_gettime", "timer_settime", "timerfd_create", "timerfd_gettime",
            "timerfd_settime", "times", "tkill", "truncate", "umask", "uname",
            "unlink", "unlinkat", "utime", "utimensat", "utimes", "vfork",
            "vmsplice", "wait4", "waitid", "write", "writev"
          ],
          "action": "SCMP_ACT_ALLOW"
        }
      ]
    }

  apparmor-default.profile: |
    #include <tunables/global>

    profile k8s-default flags=(attach_disconnected,mediate_deleted) {
      #include <abstractions/base>

      # Allow network access
      network inet tcp,
      network inet udp,
      network inet6 tcp,
      network inet6 udp,

      # Allow file system access within container
      /usr/bin/** ix,
      /bin/** ix,
      /lib/** r,
      /lib64/** r,
      /usr/lib/** r,
      /usr/lib64/** r,
      /etc/** r,
      /tmp/** rw,
      /var/tmp/** rw,
      /dev/null rw,
      /dev/zero r,
      /dev/full r,
      /dev/random r,
      /dev/urandom r,
      /proc/sys/kernel/random/uuid r,

      # Deny dangerous capabilities
      deny capability sys_admin,
      deny capability sys_module,
      deny capability sys_rawio,
      deny capability dac_override,
      deny capability dac_read_search,
      deny capability fowner,
      deny capability fsetid,
      deny capability kill,
      deny capability setgid,
      deny capability setuid,
      deny capability setpcap,
      deny capability linux_immutable,
      deny capability net_bind_service,
      deny capability net_broadcast,
      deny capability net_admin,
      deny capability net_raw,
      deny capability ipc_lock,
      deny capability ipc_owner,
      deny capability sys_chroot,
      deny capability sys_ptrace,
      deny capability sys_pacct,
      deny capability sys_boot,
      deny capability sys_nice,
      deny capability sys_resource,
      deny capability sys_time,
      deny capability sys_tty_config,
      deny capability mknod,
      deny capability lease,
      deny capability audit_write,
      deny capability audit_control,
      deny capability setfcap,
      deny capability mac_override,
      deny capability mac_admin,
      deny capability syslog,
      deny capability wake_alarm,
      deny capability block_suspend,
      deny capability audit_read,
    }

  security-context-constraints.yaml: |
    # OpenShift Security Context Constraints (if using OpenShift)
    apiVersion: security.openshift.io/v1
    kind: SecurityContextConstraints
    metadata:
      name: restricted-v2-enhanced
    allowHostDirVolumePlugin: false
    allowHostIPC: false
    allowHostNetwork: false
    allowHostPID: false
    allowHostPorts: false
    allowPrivilegedContainer: false
    allowedCapabilities: []
    defaultAddCapabilities: []
    requiredDropCapabilities:
    - ALL
    allowedUnsafeSysctls: []
    forbiddenSysctls:
    - "*"
    fsGroup:
      type: MustRunAs
      ranges:
      - min: 1
        max: 65535
    readOnlyRootFilesystem: true
    runAsUser:
      type: MustRunAsNonRoot
    seLinuxContext:
      type: MustRunAs
    supplementalGroups:
      type: MustRunAs
      ranges:
      - min: 1
        max: 65535
    volumes:
    - configMap
    - downwardAPI
    - emptyDir
    - persistentVolumeClaim
    - projected
    - secret